version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: keycloak  # Keycloak için veritabanı oluşturuluyor

    volumes:
      - db-data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8888:8080"

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    restart: always
    ports:
      - "9090:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev --db=postgres --db-url-host=db --db-username=postgres --db-password=12345 --db-url-database=keycloak
    depends_on:
      - db
    volumes:
      - keycloak-data:/opt/keycloak/data

volumes:
  db-data:
  keycloak-data:
